local locale = GetLocale()
if locale ~= "esES" and locale ~= "esMX" then return end

Cell_ExpansionData.instanceLocale = locale
Cell_ExpansionData.localizedInstanceNames = {
    -- Wrath of the Lich King
    ["La Cámara de Archavon"] = "Vault of Archavon",
    ["Naxxramas"] = "Naxxramas",
    ["El Sagrario Obsidiana"] = "The Obsidian Sanctum",
    ["El Ojo de la Eternidad"] = "The Eye of Eternity",
    ["Ulduar"] = "Ulduar",
    ["Prueba del Cruzado"] = "Trial of the Crusader",
    ["Guarida de Onyxia"] = "Onyxia's Lair",
    ["Ciudadela de la Corona de Hielo"] = "Icecrown Citadel",
    ["El Sagrario Rubí"] = "The Ruby Sanctum",
    ["Ahn'kahet: El Antiguo Reino"] = "Ahn'kahet: The Old Kingdom",
    ["Azjol-Nerub"] = "Azjol-Nerub",
    ["Fortaleza de Drak'Tharon"] = "Drak'Tharon Keep",
    ["Gundrak"] = "Gundrak",
    ["Cámaras de Relámpagos"] = "Halls of Lightning",
    ["Cámaras de Reflexión"] = "Halls of Reflection",
    ["Cámaras de Piedra"] = "Halls of Stone",
    ["Foso de Saron"] = "Pit of Saron",
    ["La Matanza de Stratholme"] = "The Culling of Stratholme",
    ["La Forja de Almas"] = "The Forge of Souls",
    ["El Nexo"] = "The Nexus",
    ["El Oculus"] = "The Oculus",
    ["El Bastión Violeta"] = "The Violet Hold",
    ["Prueba del Campeón"] = "Trial of the Champion",
    ["Fortaleza de Utgarde"] = "Utgarde Keep",
    ["Pináculo de Utgarde"] = "Utgarde Pinnacle",

    -- Burning Crusade
    ["Karazhan"] = "Karazhan",
    ["Guarida de Gruul"] = "Gruul's Lair",
    ["Guarida de Magtheridon"] = "Magtheridon's Lair",
    ["Caverna Santuario Serpiente"] = "Serpentshrine Cavern",
    ["El Castillo de la Tempestad"] = "Tempest Keep",
    ["La Cima Hyjal"] = "Hyjal Summit",
    ["Templo Oscuro"] = "Black Temple",
    ["Meseta de La Fuente del Sol"] = "Sunwell Plateau",
    ["Criptas Auchenai"] = "Auchenai Crypts",
    ["Murallas del Fuego Infernal"] = "Hellfire Ramparts",
    ["Bancal del Magister"] = "Magisters' Terrace",
    ["Tumbas de Maná"] = "Mana-Tombs",
    ["Antiguas Laderas de Trabalomas"] = "Old Hillsbrad Foothills",
    ["Salas Sethekk"] = "Sethekk Halls",
    ["Laberinto de las Sombras"] = "Shadow Labyrinth",
    ["El Arcatraz"] = "The Arcatraz",
    ["La Ciénaga Negra"] = "The Black Morass",
    ["El Horno de Sangre"] = "The Blood Furnace",
    ["El Invernáculo"] = "The Botanica",
    ["El Mechanar"] = "The Mechanar",
    ["Las Salas Arrasadas"] = "The Shattered Halls",
    ["Recinto de los Esclavos"] = "The Slave Pens",
    ["La Cámara de Vapor"] = "The Steamvault",
    ["La Sotiénaga"] = "The Underbog",

    -- Classic
    ["Núcleo de Magma"] = "Molten Core",
    ["Guarida Alanegra"] = "Blackwing Lair",
    ["Ruinas de Ahn'Qiraj"] = "Ruins of Ahn'Qiraj",
    ["Ahn'Qiraj"] = "Ahn'Qiraj",
    ["Cavernas de Brazanegra"] = "Blackfathom Deeps",
    ["Profundidades de Roca Negra"] = "Blackrock Depths",
    ["Las Minas de la Muerte"] = "The Deadmines",
    ["La Masacre"] = "Dire Maul",
    ["Gnomeregan"] = "Gnomeregan",
    ["Cumbre de Roca Negra Inferior"] = "Lower Blackrock Spire", -- esES
    ["Cumbre de Roca Negra inferior"] = "Lower Blackrock Spire", -- esMX
    ["Maraudon"] = "Maraudon",
    ["Sima Ígnea"] = "Ragefire Chasm",
    ["Zahúrda Rajacieno"] = "Razorfen Downs",
    ["Horado Rajacieno"] = "Razorfen Kraul",
    ["Monasterio Escarlata"] = "Scarlet Monastery",
    ["Scholomance"] = "Scholomance",
    ["Castillo de Colmillo Oscuro"] = "Shadowfang Keep",
    ["Stratholme"] = "Stratholme",
    ["Mazmorras de Ventormenta"] = "Stormwind Stockade",
    ["Templo Sumergido"] = "Sunken Temple",
    ["Uldaman"] = "Uldaman",
    ["Cuevas de los Lamentos"] = "Wailing Caverns",
    ["Zul'Farrak"] = "Zul'Farrak",
    ["Zul'Gurub"] = "Zul'Gurub",
}
